language: objective-c
before_install:
    - gem install cocoapods --no-rdoc --no-ri --no-document --quiet

script:
    - xcodebuild -workspace AOTestCase.xcworkspace -scheme AOTestCase -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
    - xctool test -workspace AOTestCase.xcworkspace -scheme AOTestCaseTests -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO